from makerfuncs.Area import State

STATES = {
	'europe': {
		'AL': State(
			url    = 'albania',
			nameCs = 'Albanie',
			nameEn = 'Albania',
			number = 7005,
		),
		'AD': State(
			url    = 'andorra',
			nameCs = 'Andorra',
			nameEn = 'Andorra',
			number = 7010,
		),
		'AT': State(
			url    = 'austria',
			nameCs = 'Rakousko',
			nameEn = 'Austria',
			number = 7015,
		),
		'PT-20': State(
			url    = 'azores',
			nameCs = 'Azory',
			nameEn = 'Azores',
			number = 7020,
		),
		'BY': State(
			url    = 'belarus',
			nameCs = 'Belorusko',
			nameEn = 'Belarus',
			number = 7025,
		),
		'BE': State(
			url    = 'belgium',
			nameCs = 'Belgie',
			nameEn = 'Belgium',
			number = 7030,
		),
		'BA': State(
			url    = 'bosnia-herzegovina',
			nameCs = 'Bosna a Hercegovina',
			nameEn = 'Bosnia and Herzegovina',
			number = 7035,
		),
		'BG': State(
			url    = 'bulgaria',
			nameCs = 'Bulharsko',
			nameEn = 'Bulgaria',
			number = 7040,
		),
		'HR': State(
			url    = 'croatia',
			nameCs = 'Chorvatsko',
			nameEn = 'Croatia',
			number = 7045,
		),
		'CY': State(
			url    = 'cyprus',
			nameCs = 'Kypr',
			nameEn = 'Cyprus',
			number = 7050,
		),
		'CZ': State(
			url    = 'czech-republic',
			nameCs = 'Cesko',
			nameEn = 'Czech Republic',
			number = 7055,
		),
		'DK': State(
			url    = 'denmark',
			nameCs = 'Dansko',
			nameEn = 'Denmark',
			number = 7060,
		),
		'EE': State(
			url    = 'estonia',
			nameCs = 'Estonsko',
			nameEn = 'Estonia',
			number = 7065,
		),
		'FO': State(
			url    = 'faroe-islands',
			nameCs = 'Faerske ostrovy',
			nameEn = 'Faroe Islands',
			number = 7070,
		),
		'FI': State(
			url    = 'finland',
			nameCs = 'Finsko',
			nameEn = 'Finland',
			number = 7075,
		),
		'FR': State(
			url    = 'france',
			nameCs = 'Francie',
			nameEn = 'France',
			number = 7080,
		),
		'GE': State(
			url    = 'georgia',
			nameCs = 'Gruzie',
			nameEn = 'Georgia (Eastern Europe)',
			number = 7085,
		),
		'DE': State(
			url    = 'germany',
			nameCs = 'Nemecko',
			nameEn = 'Germany',
			number = 7090,
		),
		'GB': State(
			url    = 'great-britain',
			nameCs = 'Velka Britanie',
			nameEn = 'Great Britain',
			number = 7095,
		),
		'GR': State(
			url    = 'greece',
			nameCs = 'Recko',
			nameEn = 'Greece',
			number = 7100,
		),
		'HU': State(
			url    = 'hungary',
			nameCs = 'Madarsko',
			nameEn = 'Hungary',
			number = 7105,
		),
		'IS': State(
			url    = 'iceland',
			nameCs = 'Island',
			nameEn = 'Iceland',
			number = 7110,
		),
		'IE': State(
			url    = 'ireland-and-northern-ireland',
			nameCs = 'Irsko',
			nameEn = 'Ireland',
			number = 7115,
		),
		'IM': State(
			url    = 'isle-of-man',
			nameCs = 'Man',
			nameEn = 'Isle of Man',
			number = 7120,
		),
		'IT': State(
			url    = 'italy',
			nameCs = 'Italie',
			nameEn = 'Italy',
			number = 7125,
		),
		'XK': State(
			url    = 'kosovo',
			nameCs = 'Kosovo',
			nameEn = 'Kosovo',
			number = 7130,
		),
		'LV': State(
			url    = 'latvia',
			nameCs = 'Lotyssko',
			nameEn = 'Latvia',
			number = 7135,
		),
		'LI': State(
			url    = 'liechtenstein',
			nameCs = 'Lichtenstejnsko',
			nameEn = 'Liechtenstein',
			number = 7140,
		),
		'LT': State(
			url    = 'lithuania',
			nameCs = 'Litva',
			nameEn = 'Lithuania',
			number = 7145,
		),
		'LU': State(
			url    = 'luxembourg',
			nameCs = 'Lucembursko',
			nameEn = 'Luxembourg',
			number = 7150,
		),
		'MK': State(
			url    = 'macedonia',
			nameCs = 'Severni Makedonie',
			nameEn = 'North Macedonia',
			number = 7155,
		),
		'MT': State(
			url    = 'malta',
			nameCs = 'Malta',
			nameEn = 'Malta',
			number = 7160,
		),
		'MD': State(
			url    = 'moldova',
			nameCs = 'Moldavsko',
			nameEn = 'Moldova',
			number = 7165,
		),
		'MC': State(
			url    = 'monaco',
			nameCs = 'Monako',
			nameEn = 'Monaco',
			number = 7170,
		),
		'ME': State(
			url    = 'montenegro',
			nameCs = 'Cerna Hora',
			nameEn = 'Montenegro',
			number = 7175,
		),
		'NL': State(
			url    = 'netherlands',
			nameCs = 'Nizozemsko',
			nameEn = 'Netherlands',
			number = 7180,
		),
		'NO': State(
			url    = 'norway',
			nameCs = 'Norsko',
			nameEn = 'Norway',
			number = 7185,
		),
		'PL': State(
			url    = 'poland',
			nameCs = 'Polsko',
			nameEn = 'Poland',
			number = 7190,
		),
		'PT': State(
			url    = 'portugal',
			nameCs = 'Portugalsko',
			nameEn = 'Portugal',
			number = 7195,
		),
		'RO': State(
			url    = 'romania',
			nameCs = 'Rumunsko',
			nameEn = 'Romania',
			number = 7200,
		),
		'RS': State(
			url    = 'serbia',
			nameCs = 'Srbsko',
			nameEn = 'Serbia',
			number = 7210,
		),
		'SK': State(
			url    = 'slovakia',
			nameCs = 'Slovensko',
			nameEn = 'Slovakia',
			number = 7215,
		),
		'SI': State(
			url    = 'slovenia',
			nameCs = 'Slovinsko',
			nameEn = 'Slovenia',
			number = 7220,
		),
		'ES': State(
			url    = 'spain',
			nameCs = 'Spanelsko',
			nameEn = 'Spain',
			number = 7225,
		),
		'SE': State(
			url    = 'sweden',
			nameCs = 'Svedsko',
			nameEn = 'Sweden',
			number = 7230,
		),
		'CH': State(
			url    = 'switzerland',
			nameCs = 'Svycarsko',
			nameEn = 'Switzerland',
			number = 7235,
		),
		'TR': State(
			url    = 'turkey',
			nameCs = 'Turecko',
			nameEn = 'Turkey',
			number = 7240,
		),
		'UA': State(
			url    = 'ukraine',
			nameCs = 'Ukrajina',
			nameEn = 'Ukraine (with Crimea)',
			number = 7245,
		),
	},

	'asia': {
		'AF': State(
			url    = 'afghanistan',
			nameCs = 'Afghanistan',
			nameEn = 'Afghanistan',
			number = 7305,
		),
		'AM': State(
			url    = 'armenia',
			nameCs = 'Armenie',
			nameEn = 'Armenia',
			number = 7310,
		),
		'AZ': State(
			url    = 'azerbaijan',
			nameCs = 'Azerbajdzan',
			nameEn = 'Azerbaijan',
			number = 7315,
		),
		'BD': State(
			url    = 'bangladesh',
			nameCs = 'Banglades',
			nameEn = 'Bangladesh',
			number = 7320,
		),
		'BT': State(
			url    = 'bhutan',
			nameCs = 'Bhutan',
			nameEn = 'Bhutan',
			number = 7325,
		),
		'KH': State(
			url    = 'cambodia',
			nameCs = 'Kambodza',
			nameEn = 'Cambodia',
			number = 7330,
		),
		'CN': State(
			url    = 'china',
			nameCs = 'Cina',
			nameEn = 'China',
			number = 7335,
		),
		'GCC-STATES': State(
			url    = 'gcc-states',
			nameCs = 'Rada Perskeho Zalivu',
			nameEn = 'Gulf Cooperation Council',
			number = 7340,
		),
		'IN': State(
			url    = 'india',
			nameCs = 'Indie',
			nameEn = 'India',
			number = 7345,
		),
		'ID': State(
			url    = 'indonesia',
			nameCs = 'Indonesie',
			nameEn = 'Indonesia',
			number = 7350,
		),
		'IR': State(
			url    = 'iran',
			nameCs = 'Iran',
			nameEn = 'Iran',
			number = 7355,
		),
		'IQ': State(
			url    = 'iraq',
			nameCs = 'Irak',
			nameEn = 'Iraq',
			number = 7360,
		),
		'IL-PS': State(
			url    = 'israel-and-palestine',
			nameCs = 'Izrael a Palestina',
			nameEn = 'Israel and Palestine',
			number = 7365,
		),
		'JP': State(
			url    = 'japan',
			nameCs = 'Japonsko',
			nameEn = 'Japan',
			number = 7370,
		),
		'JO': State(
			url    = 'jordan',
			nameCs = 'Jordansko',
			nameEn = 'Jordan',
			number = 7375,
		),
		'KZ': State(
			url    = 'kazakhstan',
			nameCs = 'Kazachstan',
			nameEn = 'Kazakhstan',
			number = 7380,
		),
		'KG': State(
			url    = 'kyrgyzstan',
			nameCs = 'Kyrgyzstan',
			nameEn = 'Kyrgyzstan',
			number = 7385,
		),
		'LA': State(
			url    = 'laos',
			nameCs = 'Laos',
			nameEn = 'Laos',
			number = 7390,
		),
		'LB': State(
			url    = 'lebanon',
			nameCs = 'Libanon',
			nameEn = 'Lebanon',
			number = 7395,
		),
		'MY-SG-BN': State(
			url    = 'malaysia-singapore-brunei',
			nameCs = 'Malajsie, Singapur a Brunej',
			nameEn = 'Malaysia, Singapore and Brunei',
			number = 7400,
		),
		'MV': State(
			url    = 'maldives',
			nameCs = 'Maledivy',
			nameEn = 'Maldives',
			number = 7405,
		),
		'MN': State(
			url    = 'mongolia',
			nameCs = 'Mongolsko',
			nameEn = 'Mongolia',
			number = 7410,
		),
		'MM': State(
			url    = 'myanmar',
			nameCs = 'Myanmar',
			nameEn = 'Myanmar',
			number = 7415,
		),
		'NP': State(
			url    = 'nepal',
			nameCs = 'Nepal',
			nameEn = 'Nepal',
			number = 7420,
		),
		'KP': State(
			url    = 'north-korea',
			nameCs = 'Severni Korea',
			nameEn = 'North Korea',
			number = 7425,
		),
		'PK': State(
			url    = 'pakistan',
			nameCs = 'Pakistan',
			nameEn = 'Pakistan',
			number = 7430,
		),
		'PH': State(
			url    = 'philippines',
			nameCs = 'Filipiny',
			nameEn = 'Philippines',
			number = 7435,
		),
		'KR': State(
			url    = 'south-korea',
			nameCs = 'Jizni Korea',
			nameEn = 'South Korea',
			number = 7445,
		),
		'LK': State(
			url    = 'sri-lanka',
			nameCs = 'Sri Lanka',
			nameEn = 'Sri Lanka',
			number = 7450,
		),
		'SY': State(
			url    = 'syria',
			nameCs = 'Syrie',
			nameEn = 'Syria',
			number = 7455,
		),
		'TW': State(
			url    = 'taiwan',
			nameCs = 'Tchaj-wan',
			nameEn = 'Taiwan',
			number = 7460,
		),
		'TJ': State(
			url    = 'tajikistan',
			nameCs = 'Tadzikistan',
			nameEn = 'Tajikistan',
			number = 7465,
		),
		'TH': State(
			url    = 'thailand',
			nameCs = 'Thajsko',
			nameEn = 'Thailand',
			number = 7470,
		),
		'TM': State(
			url    = 'turkmenistan',
			nameCs = 'Turkmenistan',
			nameEn = 'Turkmenistan',
			number = 7475,
		),
		'UZ': State(
			url    = 'uzbekistan',
			nameCs = 'Uzbekistan',
			nameEn = 'Uzbekistan',
			number = 7480,
		),
		'VN': State(
			url    = 'vietnam',
			nameCs = 'Vietnam',
			nameEn = 'Vietnam',
			number = 7485,
		),
		'YE': State(
			url    = 'yemen',
			nameCs = 'Jemen',
			nameEn = 'Yemen',
			number = 7490,
		),
	},

	'africa': {
		'DZ': State(
			url    = 'algeria',
			nameCs = 'Alzirsko',
			nameEn = 'Algeria',
			number = 7505,
		),
		'AO': State(
			url    = 'angola',
			nameCs = 'Angola',
			nameEn = 'Angola',
			number = 7510,
		),
		'BJ': State(
			url    = 'benin',
			nameCs = 'Benin',
			nameEn = 'Benin',
			number = 7515,
		),
		'BW': State(
			url    = 'botswana',
			nameCs = 'Botswana',
			nameEn = 'Botswana',
			number = 7520,
		),
		'BF': State(
			url    = 'burkina-faso',
			nameCs = 'Burkina Faso',
			nameEn = 'Burkina Faso',
			number = 7525,
		),
		'BI': State(
			url    = 'burundi',
			nameCs = 'Burundi',
			nameEn = 'Burundi',
			number = 7530,
		),
		'CM': State(
			url    = 'cameroon',
			nameCs = 'Kamerun',
			nameEn = 'Cameroon',
			number = 7535,
		),
		'ES-CN': State(
			url    = 'canary-islands',
			nameCs = 'Kanarske ostrovy',
			nameEn = 'Canary Islands',
			number = 7540,
		),
		'CV': State(
			url    = 'cape-verde',
			nameCs = 'Kapverdy',
			nameEn = 'Cape Verde',
			number = 7545,
		),
		'CF': State(
			url    = 'central-african-republic',
			nameCs = 'Stredoafricka republika',
			nameEn = 'Central African Republic',
			number = 7550,
		),
		'TD': State(
			url    = 'chad',
			nameCs = 'Cad',
			nameEn = 'Chad',
			number = 7555,
		),
		'KM': State(
			url    = 'comores',
			nameCs = 'Komory',
			nameEn = 'Comoros',
			number = 7560,
		),
		'CG': State(
			url    = 'congo-brazzaville',
			nameCs = 'Konzska republika',
			nameEn = 'Congo (Republic/Brazzaville)',
			number = 7565,
		),
		'CD': State(
			url    = 'congo-democratic-republic',
			nameCs = 'Konzska demokraticka republika',
			nameEn = 'Congo (Democratic Republic/Kinshasa)',
			number = 7570,
		),
		'DJ': State(
			url    = 'djibouti',
			nameCs = 'Dzibutsko',
			nameEn = 'Djibouti',
			number = 7575,
		),
		'EG': State(
			url    = 'egypt',
			nameCs = 'Egypt',
			nameEn = 'Egypt',
			number = 7580,
		),
		'GQ': State(
			url    = 'equatorial-guinea',
			nameCs = 'Rovnikova Guinea',
			nameEn = 'Equatorial Guinea',
			number = 7585,
		),
		'ER': State(
			url    = 'eritrea',
			nameCs = 'Eritrea',
			nameEn = 'Eritrea',
			number = 7590,
		),
		'ET': State(
			url    = 'ethiopia',
			nameCs = 'Etiopie',
			nameEn = 'Ethiopia',
			number = 7595,
		),
		'GA': State(
			url    = 'gabon',
			nameCs = 'Gabon',
			nameEn = 'Gabon',
			number = 7600,
		),
		'GH': State(
			url    = 'ghana',
			nameCs = 'Ghana',
			nameEn = 'Ghana',
			number = 7605,
		),
		'GN': State(
			url    = 'guinea',
			nameCs = 'Guinea',
			nameEn = 'Guinea',
			number = 7610,
		),
		'GW': State(
			url    = 'guinea-bissau',
			nameCs = 'Guinea-Bissau',
			nameEn = 'Guinea-Bissau',
			number = 7615,
		),
		'CI': State(
			url    = 'ivory-coast',
			nameCs = 'Pobrezi slonoviny',
			nameEn = 'Ivory Coast',
			number = 7620,
		),
		'KE': State(
			url    = 'kenya',
			nameCs = 'Kena',
			nameEn = 'Kenya',
			number = 7625,
		),
		'LS': State(
			url    = 'lesotho',
			nameCs = 'Lesotho',
			nameEn = 'Lesotho',
			number = 7630,
		),
		'LR': State(
			url    = 'liberia',
			nameCs = 'Liberie',
			nameEn = 'Liberia',
			number = 7635,
		),
		'LY': State(
			url    = 'libya',
			nameCs = 'Libye',
			nameEn = 'Libya',
			number = 7640,
		),
		'MG': State(
			url    = 'madagascar',
			nameCs = 'Madagaskar',
			nameEn = 'Madagascar',
			number = 7645,
		),
		'MW': State(
			url    = 'malawi',
			nameCs = 'Malawi',
			nameEn = 'Malawi',
			number = 7650,
		),
		'ML': State(
			url    = 'mali',
			nameCs = 'Mali',
			nameEn = 'Mali',
			number = 7655,
		),
		'MR': State(
			url    = 'mauritania',
			nameCs = 'Mauritanie',
			nameEn = 'Mauritania',
			number = 7660,
		),
		'MU': State(
			url    = 'mauritius',
			nameCs = 'Mauricius',
			nameEn = 'Mauritius',
			number = 7665,
		),
		'MA': State(
			url    = 'morocco',
			nameCs = 'Maroko',
			nameEn = 'Morocco',
			number = 7670,
		),
		'MZ': State(
			url    = 'mozambique',
			nameCs = 'Mosambik',
			nameEn = 'Mozambique',
			number = 7675,
		),
		'NA': State(
			url    = 'namibia',
			nameCs = 'Namibie',
			nameEn = 'Namibia',
			number = 7680,
		),
		'NE': State(
			url    = 'niger',
			nameCs = 'Niger',
			nameEn = 'Niger',
			number = 7685,
		),
		'NG': State(
			url    = 'nigeria',
			nameCs = 'Nigerie',
			nameEn = 'Nigeria',
			number = 7690,
		),
		'RW': State(
			url    = 'rwanda',
			nameCs = 'Rwanda',
			nameEn = 'Rwanda',
			number = 7695,
		),
		'SH': State(
			url    = 'saint-helena-ascension-and-tristan-da-cunha',
			nameCs = 'Svata Helena',
			nameEn = 'Saint Helena',
			number = 7700,
		),
		'ST': State(
			url    = 'sao-tome-and-principe',
			nameCs = 'Svaty Tomas a Princuv ostrov',
			nameEn = 'Sao Tome and Principe',
			number = 7705,
		),
		'SN-GM': State(
			url    = 'senegal-and-gambia',
			nameCs = 'Senegal a Gambie',
			nameEn = 'Senegal and Gambia',
			number = 7710,
		),
		'SC': State(
			url    = 'seychelles',
			nameCs = 'Seychely',
			nameEn = 'Seychelles',
			number = 7715,
		),
		'SL': State(
			url    = 'sierra-leone',
			nameCs = 'Sierra Leone',
			nameEn = 'Sierra Leone',
			number = 7720,
		),
		'SO': State(
			url    = 'somalia',
			nameCs = 'Somalsko',
			nameEn = 'Somalia',
			number = 7725,
		),
		'ZA': State(
			url    = 'south-africa',
			nameCs = 'Jizni Afrika',
			nameEn = 'South Africa',
			number = 7730,
		),
		'SS': State(
			url    = 'south-sudan',
			nameCs = 'Jizni Sudan',
			nameEn = 'South Sudan',
			number = 7735,
		),
		'SD': State(
			url    = 'sudan',
			nameCs = 'Sudan',
			nameEn = 'Sudan',
			number = 7740,
		),
		'SZ': State(
			url    = 'swaziland',
			nameCs = 'Svazijsko',
			nameEn = 'Eswatini',
			number = 7745,
		),
		'TZ': State(
			url    = 'tanzania',
			nameCs = 'Tanzanie',
			nameEn = 'Tanzania',
			number = 7750,
		),
		'TG': State(
			url    = 'togo',
			nameCs = 'Togo',
			nameEn = 'Togo',
			number = 7755,
		),
		'TN': State(
			url    = 'tunisia',
			nameCs = 'Tunisko',
			nameEn = 'Tunisia',
			number = 7760,
		),
		'UG': State(
			url    = 'uganda',
			nameCs = 'Uganda',
			nameEn = 'Uganda',
			number = 7765,
		),
		'ZM': State(
			url    = 'zambia',
			nameCs = 'Zambie',
			nameEn = 'Zambia',
			number = 7770,
		),
		'ZW': State(
			url    = 'zimbabwe',
			nameCs = 'Zimbabwe',
			nameEn = 'Zimbabwe',
			number = 7775,
		),
	},

	'north-america': {
		'CA': State(
			url    = 'canada',
			nameCs = 'Kanada',
			nameEn = 'Canada',
			number = 7805,
		),
		'GL': State(
			url    = 'greenland',
			nameCs = 'Gronsko',
			nameEn = 'Greenland',
			number = 7810,
		),
		'MX': State(
			url    = 'mexico',
			nameCs = 'Mexiko',
			nameEn = 'Mexico',
			number = 7815,
		),
		'US-AL': State(
			url    = 'us/alabama',
			nameCs = 'Alabama',
			nameEn = 'Alabama',
			number = 7820,
		),
		'US-AK': State(
			url    = 'us/alaska',
			nameCs = 'Aljaska',
			nameEn = 'Alaska',
			number = 7825,
		),
		'US-AZ': State(
			url    = 'us/arizona',
			nameCs = 'Arizona',
			nameEn = 'Arizona',
			number = 7830,
		),
		'US-AR': State(
			url    = 'us/arkansas',
			nameCs = 'Arkansas',
			nameEn = 'Arkansas',
			number = 7835,
		),
		'US-CA': State(
			url    = 'us/california',
			nameCs = 'Kalifornie',
			nameEn = 'California',
			number = 7840,
		),
		'US-CO': State(
			url    = 'us/colorado',
			nameCs = 'Colorado',
			nameEn = 'Colorado',
			number = 7845,
		),
		'US-CT': State(
			url    = 'us/connecticut',
			nameCs = 'Connecticut',
			nameEn = 'Connecticut',
			number = 7850,
		),
		'US-DE': State(
			url    = 'us/delaware',
			nameCs = 'Delaware',
			nameEn = 'Delaware',
			number = 7855,
		),
		'US-DC': State(
			url    = 'us/district-of-columbia',
			nameCs = 'Washington, D.C.',
			nameEn = 'District of Columbia',
			number = 7860,
		),
		'US-FL': State(
			url    = 'us/florida',
			nameCs = 'Florida',
			nameEn = 'Florida',
			number = 7865,
		),
		'US-GA': State(
			url    = 'us/georgia',
			nameCs = 'Georgia',
			nameEn = 'Georgia (US State)',
			number = 7870,
		),
		'US-HI': State(
			url    = 'us/hawaii',
			nameCs = 'Havaj',
			nameEn = 'Hawaii',
			number = 7875,
		),
		'US-ID': State(
			url    = 'us/idaho',
			nameCs = 'Idaho',
			nameEn = 'Idaho',
			number = 7880,
		),
		'US-IL': State(
			url    = 'us/illinois',
			nameCs = 'Illinois',
			nameEn = 'Illinois',
			number = 7885,
		),
		'US-IN': State(
			url    = 'us/indiana',
			nameCs = 'Indiana',
			nameEn = 'Indiana',
			number = 7890,
		),
		'US-IA': State(
			url    = 'us/iowa',
			nameCs = 'Iowa',
			nameEn = 'Iowa',
			number = 7895,
		),
		'US-KS': State(
			url    = 'us/kansas',
			nameCs = 'Kansas',
			nameEn = 'Kansas',
			number = 7900,
		),
		'US-KY': State(
			url    = 'us/kentucky',
			nameCs = 'Kentucky',
			nameEn = 'Kentucky',
			number = 7905,
		),
		'US-LA': State(
			url    = 'us/louisiana',
			nameCs = 'Louisiana',
			nameEn = 'Louisiana',
			number = 7910,
		),
		'US-ME': State(
			url    = 'us/maine',
			nameCs = 'Maine',
			nameEn = 'Maine',
			number = 7915,
		),
		'US-MD': State(
			url    = 'us/maryland',
			nameCs = 'Maryland',
			nameEn = 'Maryland',
			number = 7920,
		),
		'US-MA': State(
			url    = 'us/massachusetts',
			nameCs = 'Massachusetts',
			nameEn = 'Massachusetts',
			number = 7925,
		),
		'US-MI': State(
			url    = 'us/michigan',
			nameCs = 'Michigan',
			nameEn = 'Michigan',
			number = 7930,
		),
		'US-MN': State(
			url    = 'us/minnesota',
			nameCs = 'Minnesota',
			nameEn = 'Minnesota',
			number = 7935,
		),
		'US-MS': State(
			url    = 'us/mississippi',
			nameCs = 'Mississippi',
			nameEn = 'Mississippi',
			number = 7940,
		),
		'US-MO': State(
			url    = 'us/missouri',
			nameCs = 'Missouri',
			nameEn = 'Missouri',
			number = 7945,
		),
		'US-MT': State(
			url    = 'us/montana',
			nameCs = 'Montana',
			nameEn = 'Montana',
			number = 7950,
		),
		'US-NE': State(
			url    = 'us/nebraska',
			nameCs = 'Nebraska',
			nameEn = 'Nebraska',
			number = 7955,
		),
		'US-NV': State(
			url    = 'us/nevada',
			nameCs = 'Nevada',
			nameEn = 'Nevada',
			number = 7960,
		),
		'US-NH': State(
			url    = 'us/new-hampshire',
			nameCs = 'New Hampshire',
			nameEn = 'New Hampshire',
			number = 7965,
		),
		'US-NJ': State(
			url    = 'us/new-jersey',
			nameCs = 'New Jersey',
			nameEn = 'New Jersey',
			number = 7970,
		),
		'US-NM': State(
			url    = 'us/new-mexico',
			nameCs = 'Nove Mexiko',
			nameEn = 'New Mexico',
			number = 7975,
		),
		'US-NY': State(
			url    = 'us/new-york',
			nameCs = 'New York',
			nameEn = 'New York',
			number = 7980,
		),
		'US-NC': State(
			url    = 'us/north-carolina',
			nameCs = 'Severni Karolina',
			nameEn = 'North Carolina',
			number = 7985,
		),
		'US-ND': State(
			url    = 'us/north-dakota',
			nameCs = 'Severni Dakota',
			nameEn = 'North Dakota',
			number = 7990,
		),
		'US-OH': State(
			url    = 'us/ohio',
			nameCs = 'Ohio',
			nameEn = 'Ohio',
			number = 7995,
		),
		'US-OK': State(
			url    = 'us/oklahoma',
			nameCs = 'Oklahoma',
			nameEn = 'Oklahoma',
			number = 8000,
		),
		'US-OR': State(
			url    = 'us/oregon',
			nameCs = 'Oregon',
			nameEn = 'Oregon',
			number = 8005,
		),
		'US-PA': State(
			url    = 'us/pennsylvania',
			nameCs = 'Pennsylvania',
			nameEn = 'Pennsylvania',
			number = 8010,
		),
		'PR': State(
			url    = 'us/puerto-rico',
			nameCs = 'Portoriko',
			nameEn = 'Puerto Rico',
			number = 8015,
		),
		'US-RI': State(
			url    = 'us/rhode-island',
			nameCs = 'Rhode Island',
			nameEn = 'Rhode Island',
			number = 8020,
		),
		'US-SC': State(
			url    = 'us/south-carolina',
			nameCs = 'Jizni Karolina',
			nameEn = 'South Carolina',
			number = 8025,
		),
		'US-SD': State(
			url    = 'us/south-dakota',
			nameCs = 'Jizni Dakota',
			nameEn = 'South Dakota',
			number = 8030,
		),
		'US-TN': State(
			url    = 'us/tennessee',
			nameCs = 'Tennessee',
			nameEn = 'Tennessee',
			number = 8035,
		),
		'US-TX': State(
			url    = 'us/texas',
			nameCs = 'Texas',
			nameEn = 'Texas',
			number = 8040,
		),
		'US-UT': State(
			url    = 'us/utah',
			nameCs = 'Utah',
			nameEn = 'Utah',
			number = 8045,
		),
		'US-VT': State(
			url    = 'us/vermont',
			nameCs = 'Vermont',
			nameEn = 'Vermont',
			number = 8050,
		),
		'US-VA': State(
			url    = 'us/virginia',
			nameCs = 'Virginia',
			nameEn = 'Virginia',
			number = 8055,
		),
		'US-WA': State(
			url    = 'us/washington',
			nameCs = 'Washington',
			nameEn = 'Washington',
			number = 8060,
		),
		'US-WV': State(
			url    = 'us/west-virginia',
			nameCs = 'West Virginia',
			nameEn = 'West Virginia',
			number = 8065,
		),
		'US-WI': State(
			url    = 'us/wisconsin',
			nameCs = 'Wisconsin',
			nameEn = 'Wisconsin',
			number = 8070,
		),
		'US-WY': State(
			url    = 'us/wyoming',
			nameCs = 'Wyoming',
			nameEn = 'Wyoming',
			number = 8075,
		),
	},

	'central-america': {
		'BS': State(
			url    = 'bahamas',
			nameCs = 'Bahamy',
			nameEn = 'Bahamas',
			number = 8105,
		),
		'BZ': State(
			url    = 'belize',
			nameCs = 'Belize',
			nameEn = 'Belize',
			number = 8110,
		),
		'CU': State(
			url    = 'cuba',
			nameCs = 'Kuba',
			nameEn = 'Cuba',
			number = 8115,
		),
		'GT': State(
			url    = 'guatemala',
			nameCs = 'Guatemala',
			nameEn = 'Guatemala',
			number = 8120,
		),
		'HT-DO': State(
			url    = 'haiti-and-domrep',
			nameCs = 'Haiti a Dominikanska republika',
			nameEn = 'Haiti and Dominican Republic',
			number = 8125,
		),
		'JM': State(
			url    = 'jamaica',
			nameCs = 'Jamajka',
			nameEn = 'Jamaica',
			number = 8130,
		),
		'NI': State(
			url    = 'nicaragua',
			nameCs = 'Nikaragua',
			nameEn = 'Nicaragua',
			number = 8135,
		),
	},

	'south-america': {
		'AR': State(
			url    = 'argentina',
			nameCs = 'Argentina',
			nameEn = 'Argentina',
			number = 8205,
		),
		'BO': State(
			url    = 'bolivia',
			nameCs = 'Bolivie',
			nameEn = 'Bolivia',
			number = 8210,
		),
		'BR': State(
			url    = 'brazil',
			nameCs = 'Brazilie',
			nameEn = 'Brazil',
			number = 8215,
		),
		'CL': State(
			url    = 'chile',
			nameCs = 'Chile',
			nameEn = 'Chile',
			number = 8220,
		),
		'CO': State(
			url    = 'colombia',
			nameCs = 'Kolumbie',
			nameEn = 'Colombia',
			number = 8225,
		),
		'EC': State(
			url    = 'ecuador',
			nameCs = 'Ekvador',
			nameEn = 'Ecuador',
			number = 8230,
		),
		'PY': State(
			url    = 'paraguay',
			nameCs = 'Paraguay',
			nameEn = 'Paraguay',
			number = 8235,
		),
		'PE': State(
			url    = 'peru',
			nameCs = 'Peru',
			nameEn = 'Peru',
			number = 8240,
		),
		'SR': State(
			url    = 'suriname',
			nameCs = 'Surinam',
			nameEn = 'Suriname',
			number = 8245,
		),
		'UY': State(
			url    = 'uruguay',
			nameCs = 'Uruguay',
			nameEn = 'Uruguay',
			number = 8250,
		),
		'VE': State(
			url    = 'venezuela',
			nameCs = 'Venezuela',
			nameEn = 'Venezuela',
			number = 8255,
		),
	},

	'australia-oceania': {
		'AU': State(
			url    = 'australia',
			nameCs = 'Australie',
			nameEn = 'Australia',
			number = 8305,
		),
		'FJ': State(
			url    = 'fiji',
			nameCs = 'Fidzi',
			nameEn = 'Fiji',
			number = 8310,
		),
		'NC': State(
			url    = 'new-caledonia',
			nameCs = 'Nova Kaledonie',
			nameEn = 'New Caledonia',
			number = 8315,
		),
		'NZ': State(
			url    = 'new-zealand',
			nameCs = 'Novy Zeland',
			nameEn = 'New Zealand',
			number = 8320,
		),
		'PG': State(
			url    = 'papua-new-guinea',
			nameCs = 'Papua Nova Guinea',
			nameEn = 'Papua New Guinea',
			number = 8325,
		),
	},

	'russia': {
		'RU-CFO': State(
			url    = 'central-fed-district',
			nameCs = 'Centralni federalni okruh',
			nameEn = 'Central Federal District',
			number = 8330,
		),
		'RU-KFO': State(
			url    = 'crimean-fed-district',
			nameCs = 'Krymsky federalni okruh',
			nameEn = 'Crimean Federal District',
			number = 8335,
		),
		'RU-DFO': State(
			url    = 'far-eastern-fed-district',
			nameCs = 'Dalnevychodni federalni okruh',
			nameEn = 'Far Eastern Federal District',
			number = 8340,
		),
		'RU-SKFO': State(
			url    = 'north-caucasus-fed-district',
			nameCs = 'Severokavkazsky federalni okruh',
			nameEn = 'North Caucasus Federal District',
			number = 8345,
		),
		'RU-SZFO': State(
			url    = 'northwestern-fed-district',
			nameCs = 'Severozapadni federalni okruh',
			nameEn = 'Northwestern Federal District',
			number = 8350,
		),
		'RU-SFO': State(
			url    = 'siberian-fed-district',
			nameCs = 'Sibirsky federalni okruh',
			nameEn = 'Siberian Federal District',
			number = 8355,
		),
		'RU-UFO': State(
			url    = 'south-fed-district',
			nameCs = 'Jizni federalni okruh',
			nameEn = 'South Federal District',
			number = 8360,
		),
		'RU-URALFO': State(
			url    = 'ural-fed-district',
			nameCs = 'Uralsky federalni okruh',
			nameEn = 'Ural Federal District',
			number = 8365,
		),
		'RU-PFO': State(
			url    = 'volga-fed-district',
			nameCs = 'Povolzsky federalni okruh',
			nameEn = 'Volga Federal District',
			number = 8370,
		),
		'RU-KLGD': State(
			url    = 'kaliningrad',
			nameCs = 'Kaliningrad',
			nameEn = 'Kaliningrad',
			number = 8375,
		),
	},
}


continentNames = {
	'europe': 'Evropa',
	'asia': 'Asie',
	'africa': 'Afrika',
	'north-america': 'Severní Amerika',
	'central-america': 'Střední Amerika',
	'south-america': 'Jižní Amerika',
	'australia-oceania': 'Austrálie a Oceánie',
	'russia': 'Rusko'
}
